const  ActionTypes = {
    GET_OFFERS_LIST: "GET_OFFERS_LIST",
    GET_AIRPOTS_LIST: "GET_AIRPOTS_LIST",
    SET_CITY_CODE_MAP: "SET_CITY_CODE_MAP",
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER"
};

export default ActionTypes;
